### PR TITLE
chore(initial-setup): Initial setup for hapi (composer, config, logging, linting, testing)

### PR DESCRIPTION
**Pull request by apurvajain**
Please refer to readme.md for more details.

### CODE REVIEW

**Comment by telkomsel-machine-user** [comment]
Can one of the admins verify this patch?

**Comment by apurvajain** [comment]
retest this please

**Comment by apurvajain** [comment]
add to whitelist

**Comment by apurvajain** [comment]
retest this please

**Comment by apurvajain** [comment]
retest this please

**Comment by apurvajain** [comment]
retest this please

**Pull request merged**
